### ISSUE TITLE
Falscher Pfad in 'script/postfix.sh'

### ISSUE THREAD

**Issue by b0ykoe** [shoujii/Next-Server-Buster#1]
Zeile 21/40 und 22/40
cp /root/NeXt-Server-Buster/configpostfix/master.cf /etc/postfix/master.cf
cp /root/NeXt-Server-Buster/configpostfix/submission_header_cleanup /etc/postfix/submission_header_cleanup

Bei configpostfix fehlt ein Slash.

Viele Grüße & Stay safe!

**Comment by b0ykoe** [comment]
`./script/roundcube.sh:33:cp /root/NeXt-Server-Buster/configroundcube/config.inc.php /var/www/${MYDOMAIN}/public/webmail/config/config.inc.php`

Hier ists ebenfalls falsch

**Comment by shoujii** [comment]
Danke für die Hinweise, ich werde es direkt verbessern!
Ich habe die letzten Tage im Script viel verändert u.a. die sed Befehle durch eine Funktion ersetzt und da search and replace genutzt... da muss es wohl ein paar Pfade erwischt haben :dagger: 
Im Moment sollte ich das Repo wohl als Testing kennzeichnen, da ich die Scripts stark überarbeiten möchte.

Gruß,
Marcel

**Comment by b0ykoe** [comment]
Ich verstehe. Ich bin momentan dabei das Script einmal durchzugehen und hab noch einen gefunden.

An error occurred in line 62 of file /root/NeXt-Server-Buster/script/firewall.sh:
   sed_replace_word "^OPEN_TCP=.*/OPEN_TCP=\"${SSH_PORT}, 25, 80, 110, 143, 443, 465, 587, 993, 995, 4000\"/" "/etc/arno-iptables-firewall/firewall.conf"

**Comment by shoujii** [comment]
Die ersetzten sed's sind noch alle nicht getestet, da ist die Zeit ausgegangen.
Da dürfte einiges kaputt sein, bzw. noch angepasst werden, damit die Befehle mit der Funktion klappen.

Ich bin nicht davon ausgegangen dass das Script noch überhaupt wer nutzt um ehrlich zu sein.

**Comment by b0ykoe** [comment]
Ah. Dann warte ich lieber nochmal. Ich hab euer Projekt damals schon benutzt und fand es eigentlich immer top. Bin dann aus zufall wieder drauf gestoßen und dachte mir "probier ichs mal aus".

**Comment by shoujii** [comment]
Bis vor 7 Tagen hat es auch einwandfrei funktioniert, bis ich es weiter verbessern wollte und mir dann mittendrin die Zeit dazwischen gegrätscht ist :D

Bis auf die sed Befehle funktioniert aber definitiv alles, ich hatte es vor der Änderung getestet.
Heißt wenn ich die Befehle teste und fixe dann läuft wieder alles :)

Es ist halt für die Zukunft besser, je mehr ich so Sachen vereinheitliche und in Funktionen packe, dann kann ich bessere Fehler ausgeben und versuchen Fehler zu vermeiden -> bei der neuen sed Funktion escaped er slashes automatisch.

**Comment by b0ykoe** [comment]
Perfekt, habt ihr mal daran gedacht nen Discord dafür zu erstellen? Dann könnte man sich da austauschen :P

**Comment by shoujii** [comment]
https://discord.gg/tncTVz

Das ist er schon :)
