### ISSUE TITLE
costum paths

### ISSUE THREAD

**Issue by shoujii** [shoujii/NeXt-Server-Buster#18]
allow costum paths for nextcloud etc..

but check:
what if the costum path is used by another addon?

**Comment by shoujii** [comment]
used paths:

pma
webmail
wordpress
root
munin
nextcloud
rspamd

**Comment by shoujii** [comment]
root@nxt:~/NeXt-Server-Buster/configs# cat blocked_paths.conf
webmail
rspamdmunin

müssen beim adden getrennt werden

**Comment by BoBBer446** [comment]
if [ -d "$DIRECTORY" ]; then
echo "sorry, dir exist, try another one
 fi

Maybe use a function to check

**Comment by shoujii** [comment]
https://github.com/shoujii/NeXt-Server-Buster/blob/master/configs/blocked_paths.conf

Da werden feste Pfade eingetragen.

Jedes Addon trägt dann seinen Pfad ein in die Datei (Vorteil die Datei bleibt auch nach beenden des Scripts erhalten).
https://github.com/shoujii/NeXt-Server-Buster/blob/master/addons/nextcloud.sh
echo "$NEXTCLOUD_PATH_NAME" >> ${SCRIPT_PATH}/configs/blocked_paths.conf

Die Menüs nutzen die Datei um bereits genutzte Pfade zu verbieten:
https://github.com/shoujii/NeXt-Server-Buster/blob/master/menus/nextcloud_menu.sh

array=($(cat "${SCRIPT_PATH}/configs/blocked_paths.conf"))
Datei wird in array eingelesen.

printf -v array_str -- ',,%q' "${array[@]}"
Escape Sonderzeichen 

if [[ "${array_str},," =~ ,,${NEXTCLOUD_PATH_NAME},, ]]
Ist in array_str der vom Nutzer gewählte Pfad schon drin?

Problem ist das die Addons ihre Pfade nicht in eine neue Zeile in der Datei eintragen sondern hinter den letzten wert, dass muss noch gefixt werden

**Comment by shoujii** [comment]
+ munin costum path hinzugefügt

Die Methode mit blocked_paths.conf funktioniert.
Die Paths werden auch in der Userconfig eingetragen, dass hat keinen Wert für das Script, aber vll nochmal als User Info drin lassen?

**Comment by shoujii** [comment]
Das selbe System habe ich hier https://github.com/shoujii/NeXt-Server-Buster/commit/7e3895e79694845bcabca5b524a403003a66097d auch für die geblockten Ports genutzt.

Zusätzlich werden bei der Teamspeak Addon Installation die Ports auch dazu geaddet.
Gibt es noch irgendwo Ports im Script außer SSH und Teamspeak3?
