### ISSUE TITLE
mailserver missconfiguration

### ISSUE THREAD

**Issue by b0ykoe** [shoujii/Next-Server-Buster#2]
After using the default mailserver the mailserver has to be reconfigured

File:
/var/www/DOMAIN/public/webmail/config/defaults.inc.php

Options to reconfigure from their defaultvalue:

$config['smtp_server'] = 'tls://%n';

$config['smtp_conn_options'] = array(
'ssl' => array(
'verify_peer' => false,
'verify_peer_name' => false,
),
);

**Comment by shoujii** [comment]
Hey,

ich war im Urlaub und konnte daher nichts verändern.
In der nächsten Woche habe ich Zeit und ändere es :)

Gruß

**Comment by shoujii** [comment]
Ich merke leider, dass es zeitlich nicht mehr klappt das Script zu warten.
Aus diesem Grund ich meine Repositories archivieren, dann kann es jeder frei nutzen und weiter entwickeln.
