### ISSUE TITLE
Fail2Ban configuration

### ISSUE THREAD

**Issue by VeePay** [shoujii/NeXt-Server-Buster#46]
- Konfigurationsmöglichkeit übers Skript hinzufügen
- Statusabfrage hinzufügen

**Comment by shoujii** [comment]
Das ist im Grunde eine gute Idee, wobei ich finde das Leute die sich mit so Fragen beschäftigen auch sicher selbst wissen an welchen Schrauben sie drehen müssen :O
Da ich aus Zeitgründen das Script eher schlank halten muss und nach der Buster Version die Entwicklung wohl eh eingestellt wird, close ich das Issue.
