### ISSUE TITLE
Erweiterung der Config/mailserver/database.sql

### ISSUE THREAD

**Issue by axiades** [shoujii/NeXt-Server-Buster#49]
Hallo Ich habe hier eine Kleine Erweiterung die gern extra oder dierekt mit in die Datenbank eingespielt werden sollte zur sicherheit des Mailservers..

[https://gist.githubusercontent.com/ThomasLeister/c9d16205318ab3dc68b13923a6ceab93/raw/6ae2ee86d42ec280f3459d09d20f4ef800da4cab/tlspolicies.sql](url)

**Comment by shoujii** [comment]
Hey :)

Ist der link richtig?

**Comment by BoBBer446** [comment]
Ist er nicht :smile:

**Comment by BoBBer446** [comment]
https://gist.githubusercontent.com/ThomasLeister/c9d16205318ab3dc68b13923a6ceab93/raw/6ae2ee86d42ec280f3459d09d20f4ef800da4cab/tlspolicies.sql

**Comment by shoujii** [comment]
Das schaut doch super aus :)
Ich werde schauen das ich die Tage dazu komme es einzubauen.
Im Moment gibt es mit lets encrypt und dem Erinnerungs Cronjob noch eine große Baustelle 🙈🙈

**Comment by shoujii** [comment]
Ich habe es geaddet:
https://github.com/shoujii/NeXt-Server-Buster/commit/0eb09ae21f8b07c7fc4f14a7dc187d96bcb75c54

Ist noch ungetestet, aber sollte laufen :)
Gerade läuft die Lets Encrypt Integration
